### ISSUE TITLE
[건의]보안을 위한 식별키 생성 알고리즘 필요성

### ISSUE THREAD

**Issue by LJG070** [Studyvelopers/OverTheFlow#29]
### 주제
DB테이블마다 노출되는 식별키를 보안을 위해 암호화 시켜야 한다고 생각합니다
sha 해시 알고리즘같은 알고리즘으로 테이블의 식별키들을 암호화 시켜서
외부에 노출되더라도 쉽게 식별할 수 없도록 만드는 것이 좋을 것 같습니다

**Comment by dhjeon1993** [comment]
resolved: #30
